### ISSUE TITLE
DrugZ: IndexError: single positional indexer is out-of-bounds

### ISSUE THREAD

**Issue by apacis** [hart-lab/drugz#12]
Hello,

I'm trying to run DrugZ, but getting the error below.
Is this a panda issue? I tried both version 1.5.3 and 2.2.3

[pacisala@narval1 drugz]$ drugz/drugz.py -i sgRNA_count.txt -o drugz-output.txt -c T15_A_control,T15_B_control -x T15_A_olaparib,T15_B_olaparib

INFO:__main__:Initiating analysis
INFO:__main__:Loading the read count matrix
INFO:__main__:Normalizing read counts
INFO:__main__:Calculating raw fold change for replicate 1
Traceback (most recent call last):
  File "drugz/drugz.py", line 481, in <module>
    main()
  File "drugz/drugz.py", line 478, in main
    drugZ_analysis(args)
  File "drugz/drugz.py", line 447, in drugZ_analysis
    fold_change, fc_zscore_id = empirical_bayes(fold_change=fold_change, half_window_size=args.half_window_size,
  File "drugz/drugz.py", line 187, in empirical_bayes
    results = fold_change.iloc[no_of_guides - (half_window_size + 1)][empirical_bayes_id]
  File "/home/pacisala/bin/drugz/lib/python3.8/site-packages/pandas/core/indexing.py", line 1073, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/home/pacisala/bin/drugz/lib/python3.8/site-packages/pandas/core/indexing.py", line 1625, in _getitem_axis
    self._validate_integer(key, axis)
  File "/home/pacisala/bin/drugz/lib/python3.8/site-packages/pandas/core/indexing.py", line 1557, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds

Thank you,
Alain

**Comment by gaithdroby** [comment]
@apacis Try running the script on sgRNA count data frame with at least 251 lines. 250 sgRNAs is the minimum needed. Here is a working sample file. 

Running DrugZ command:
`drugz.py -i sgRNA_count_example.txt -o drugz_output_example.txt -c Control_R1,Control_R2,Control_R3 -x Treated_R1,Treated_R2,Treated_R3`

[sgRNA_count_example.txt](https://github.com/user-attachments/files/18559861/sgRNA_count_example.txt)
