### ISSUE TITLE
Error while running drugz

### ISSUE THREAD

**Issue by ghoshal** [hart-lab/drugz#4]
Hi,

I am getting the following error while running drugz. Do you have any idea why it might be happening?

Traceback (most recent call last):
  File "/Users/bibaswan/Documents/programs/drugz/drugz.py", line 242, in <module>
    main()
  File "/Users/bibaswan/Documents/programs/drugz/drugz.py", line 238, in main
    args.fc_outfile, remove_genes, args.pseudocount, args.minObs, args.half_window_size, args.index_column, not args.quiet)
  File "/Users/bibaswan/Documents/programs/drugz/drugz.py", line 113, in drugz
    if (ebstd >= fc[eb_std_samplid][i-1]):
  File "/Users/bibaswan/anaconda/lib/python3.5/site-packages/pandas/core/series.py", line 623, in __getitem__
    result = self.index.get_value(self, key)
  File "/Users/bibaswan/anaconda/lib/python3.5/site-packages/pandas/core/indexes/base.py", line 2560, in get_value
    tz=getattr(series.dtype, 'tz', None))
  File "pandas/_libs/index.pyx", line 83, in pandas._libs.index.IndexEngine.get_value
  File "pandas/_libs/index.pyx", line 91, in pandas._libs.index.IndexEngine.get_value
  File "pandas/_libs/index.pyx", line 139, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 811, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 817, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 499

Thanks,

Bibaswan

**Comment by mcolic** [comment]
Hi Bibaswan, 

I can take a look of it. Do you mind sharing your input file (mcolic@mdanderson.org), and I ll check it.

Best,
Medina
